// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqguwfegtbpltdhtewmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZ3V3ZmVndGJwbHRkaHRld21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MzQwNDYsImV4cCI6MjA2NTExMDA0Nn0.e59qJEAh4itD949G5RN7DzUwo3pBkTaXiHVOUu3OT6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);